@include('frontpannel/customer1/head')
@include('frontpannel/customer1/header')
@include('frontpannel/customer1/sidebar')
@include('frontpannel/customer1/dashboard')
@include('frontpannel/customer1/footer')